### ISSUE TITLE
this error come everytime run this app

### ISSUE THREAD

**Issue by amayra** [nov0caina/NetControl#4]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ArpForm'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.Show()
   at SelfishNetv0.main.AbrirFormulario[MiForm](Func`1 metodofactory) in C:\Users\amayra\Downloads\Compressed\SelfishNetV3-master_2\SelfishNetv0\main.cs:line 290
   at SelfishNetv0.main.btnARP_Click(Object sender, EventArgs e) in C:\Users\amayra\Downloads\Compressed\SelfishNetV3-master_2\SelfishNetv0\main.cs:line 224
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nov0caina** [comment]
Hello @amayra,

This exception (`System.ObjectDisposedException` in `ArpForm`) was an architectural limitation of the legacy Windows Forms UI.

In **NetControl v1.0.0**, the entire WinForms presentation layer and `ArpForm` have been retired and replaced with a cross-platform **Avalonia UI 11** desktop application on **.NET 8 LTS**. There are no longer any WinForms handle lifecycle issues or ObjectDisposed exceptions.

You can download the new release at:
https://github.com/nov0caina/NetControl/releases/tag/v1.0.0

Closing this issue as resolved.
