### ISSUE TITLE
There are still old problems

### ISSUE THREAD

**Issue by staaandup** [nov0caina/NetControl#6]
Hello there, @nov0nov0caina. Thank you for the update! and please forgive me for saying this, but i don't see any difference between this release and the previous one other than the new ui. also, i noticed that a couple of previously existing problems are still present in this release, as well as new ones.
1. The error message that appears when you run the app, as previously reported [here](https://github.com/nov0caina/SelfishNetV3/issues/4#issue-780868903) by @amayra
![selfishproblem1](https://user-images.githubusercontent.com/50317210/177098610-a2b22c82-5f85-4e03-b9c3-866a6a30b751.png)
2. (New issue) You cannot exit the app from the nic selection* window. you must use the small exit button at the top right of the app.
![selfishproblem2](https://user-images.githubusercontent.com/50317210/177098707-b6147922-efdd-4cbc-8069-f9fbef1e71b8.png)
3. The text in the exit message box in the exit confirmation window is in spanish.
![selfishproblem3](https://user-images.githubusercontent.com/50317210/177098722-7b68e3ef-ec1f-42c5-930a-ec20db7655b3.png)
4. After using the app one or two times, the icon of SelfishNetv3.exe vanishes.
![selfishproblem4](https://user-images.githubusercontent.com/50317210/177098735-9be40eec-7470-4a91-8bb5-20f0658b9e60.png)

Gif
![selfishproblemGIF](https://user-images.githubusercontent.com/50317210/177098830-1c4b2fe5-ffa5-4a5e-ad9f-00195318005d.gif)

and here is the complete error message

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: InvalidArgument=Value of '3' is not valid for 'SelectedIndex'.
> Parameter name: SelectedIndex
>    at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>    at SelfishNetv3.CAdapter.CAdapter_Shown(Object sender, EventArgs e)
>    at System.Windows.Forms.Form.OnShown(EventArgs e)
>    at System.Windows.Forms.Form.CallShownEvent()
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.runTryCode(Object userData)
>    at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
> ----------------------------------------
> SelfishNetv3
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/My%20Programs/SelfishNetV3/SelfishNetv3.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8663 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 3.5.0.0
>     Win32 Version: 3.5.30729.8674 built by: QFE
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> PcapNet
>     Assembly Version: 1.0.2632.24367
>     Win32 Version: 
>     CodeBase: file:///D:/My%20Programs/SelfishNetV3/PcapNet.DLL
> ----------------------------------------
> msvcm80
>     Assembly Version: 8.0.50727.9185
>     Win32 Version: 8.00.50727.9185
>     CodeBase: file:///C:/Windows/WinSxS/x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9185_none_d0905a48442809b8/msvcm80.dll
> ----------------------------------------
> ExpandableGridView
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/My%20Programs/SelfishNetV3/ExpandableGridView.DLL
> ----------------------------------------
> DataGridViewNumericUpDownElements
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/My%20Programs/SelfishNetV3/DataGridViewNumericUpDownElements.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.50727.8662 (QFE.050727-8600)
>     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by nov0caina** [comment]
Hello @staaandup,

The legacy WinForms handle crash (`ObjectDisposedException` reported in #4) and associated UI instability have been permanently eliminated.

**NetControl v1.0.0** completely rebuilds the UI on **.NET 8 LTS** using modern **Avalonia UI**, removing obsolete WinForms code and P/Invoke `user32.dll` handle allocations. In addition, NetControl natively supports modern **Npcap** on Windows and **libpcap** on Linux/macOS.

Check out the official v1.0.0 release:
https://github.com/nov0caina/NetControl/releases/tag/v1.0.0

Closing this issue as resolved.
